[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.build]
cmds = ["npm ci --prefer-offline --no-audit", "npm run build"]

[phases.start]
cmd = "npx serve -s dist/test2 -l 3000"

[variables]
NODE_ENV = "production"
PORT = "3000"
