[variables]
NODE_ENV = "production"
NIXPACKS_PATH = ".nixpacks"

[phases.install]
commands = ["npm ci --omit=dev --prefer-offline --no-audit"]

[phases.build]
commands = ["npm run build"]

[cache]
paths = []
